# Generated by Django 2.0.7 on 2018-07-14 08:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', main.models.SiteUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('type', models.SmallIntegerField(choices=[(0, '通告'), (1, '新闻')], default=0, verbose_name='类型')),
                ('index', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否加入首页')),
                ('change_show', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否加入轮播图')),
                ('top', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='置顶')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='日期')),
                ('big_img_path', models.CharField(max_length=64, verbose_name='大图')),
                ('small_img_path', models.CharField(max_length=64, verbose_name='小图')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='SiteGroup',
            fields=[
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='SitePermission',
            fields=[
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.AddField(
            model_name='siteuser',
            name='groups',
            field=models.ManyToManyField(to='main.SiteGroup', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上级用户'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='main.SitePermission', verbose_name='user permissions'),
        ),
    ]
